[package]
name = "advent-of-code-2022"

version = "1.0.0"
edition = "2021"
authors = ["DLKJ"]
license = "BSD-2-Clause"

[dependencies]
anyhow = "1.0"
itertools = "0.10"
nom = "7.1"

[dev-dependencies]
criterion = "0.4"

[[bench]]
name = "solution_benchmarks"
harness = false
