[target.'cfg(all())']
rustflags = [
    "-C", "target-cpu=native",
    # Global lints/warnings.
    "-Dunsafe_code",
    "-Wclippy::all",
    "-Wclippy::pedantic",
    "-Wclippy::nursery",
    "-Wclippy::unwrap_used",
    "-Wclippy::expect_used",
    "-Aclippy::missing-errors-doc"
]

[profile.release]
lto = "fat"
panic = "abort"
incremental = false
codegen-units = 1
debug = true