[target.'cfg(all())']
rustflags = [
    # Global lints/warnings.
    "-Dunsafe_code",
    "-Wclippy::all",
    "-Wclippy::pedantic",
    "-Wclippy::nursery",
    "-Wclippy::unwrap_used",
    "-Wclippy::expect_used"
]